# Generated by Django 3.2.16 on 2022-10-06 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminExpensa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_nombre', models.CharField(max_length=100, unique=True)),
                ('bloque', models.CharField(max_length=100)),
                ('costoExpensa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_Entrega', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminExpensa.propietario')),
            ],
        ),
    ]
