# Generated by Django 3.2.16 on 2022-10-06 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminExpensa', '0002_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expensa_Agua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Expensa_Agua', models.CharField(max_length=100, unique=True)),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.CharField(max_length=100)),
                ('anio', models.CharField(max_length=100)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminExpensa.departamento')),
            ],
        ),
    ]
