# Generated by Django 3.2.16 on 2022-10-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminExpensa', '0003_expensa_agua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_Expensa', models.CharField(max_length=100)),
                ('anio_Expensa', models.CharField(max_length=100)),
                ('estado_Expensa', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminExpensa.departamento')),
            ],
        ),
    ]
